language: node_js

node_js:
  - "0.10"
  - "0.8"

sudo: false

install:
  - travis_retry npm install
  - travis_retry npm update
  - travis_retry npm prune

script:
  - ./node_modules/jest-cli/bin/jest.js

cache:
  directories:
    - node_modules

